### ISSUE TITLE
Reverse related elements

### ISSUE THREAD

**Issue by joshuabaker** [studioespresso/craft-scout#132]
Would it be possible to trigger a sync when related elements are saved?

For example, when someone edits a category title all of the entries that have that category would sync.

We’ve put together this snippet, which is working via `Element::EVENT_AFTER_SAVE` in a module.

```php
/**
 * @param \craft\base\Element $element
 *
 * @throws \Exception
 */
public function updateReverseRelated(Element $element)
{
    $indicies = Scout::$plugin->getSettings()->getIndices();

    /** @var \rias\scout\ScoutIndex $index */
    foreach ($indicies as $index) {
        $criteria = clone $index->criteria;

        $relatedElements = $criteria
            ->relatedTo([
                'targetElement' => $element,
            ])
            ->limit(null)
            ->all();

        /** @var \rias\scout\behaviors\SearchableBehavior $relatedElement */
        foreach ($relatedElements as $relatedElement) {
            $relatedElement->searchable(false);
        }
    }
}
```

**Comment by timkelty** [comment]
Certainly, I've had use for this as well.

So what you have is working, but you're suggesting maybe we bake that in, or enable it behind an option?

**Comment by joshuabaker** [comment]
Definitely baked in somehow. Behind an option that’s enabled by default, would be my suggestion.

**Comment by timkelty** [comment]
@joshuabaker sounds good. I have some planned upgrades in the works, so I'll try to include this.

**Comment by joshuabaker** [comment]
Going to close as stale. If anyone wants this feature, please consider opening another issue.
