### ISSUE TITLE
Exception if mappings is present but indicies is not

### ISSUE THREAD

**Issue by joshuabaker** [studioespresso/craft-scout#133]
Just found one of our older projects still had `mappings` in the config file whilst using Scout v2.

Could/should an exception be thrown where `mappings` is present and `indicies` is not?

**Comment by timkelty** [comment]
Seems like a good idea @joshuabaker

**Comment by joshuabaker** [comment]
Going to close as stale. If anyone wants this feature, please consider opening another issue.
