### ISSUE TITLE
Use Field (MultiSelect) values as an index

### ISSUE THREAD

**Issue by davebeesley** [studioespresso/craft-scout#140]
Hi,
Is it possible to access the options on a MultiSelect field, and use scout to create an index from them?

Edge use case I know. But this would be super handy.

**Comment by timkelty** [comment]
🤔... @davebeesley which options specifically? Can you sketch up what you think the field is oils look like?

**Comment by timkelty** [comment]
Or are you just saying using an existing multi select and using the values in your index?

**Comment by davebeesley** [comment]
Yeah, that is the one. Taking the possible values in an existing Multi select field in Craft. And then using them to generate an index for searching with (ie. Job Role)

**Comment by timkelty** [comment]
@davebeesley certainly possible…

To clarify:

- Where does this field live, a global?
- So you want a scout index for each option in your select? Does the selected value mean anything then?

**Comment by davebeesley** [comment]
Hey @timkelty 
The field is on a section (channel) for "Employees"
I want to index the options - So say an index called `job_roles` would have entries called, 'Boss', 'Cleaner', 'Receptionist'
We then use this to populate a field on our search page. As all employees will be tagged with job roles.
Basically, when the client adds new job roles, we want to use scout to keep everything in sync, save manually intervening and adding them to the algolia index ourselves

**Comment by timkelty** [comment]
@davebeesley Sure, I'll post an example of what you're after, but it also seems like there might be other options. Seems like multiple indices isn't really necessary if you use filtering instead.

Can you outline what the end goal is (ie what shows up on your search page)?

Are we talking about a listing of employees with a facet filter for `job_roles`?
Or a dedicated page for each job role that is pre-filtered?
Or something else?

**Comment by davebeesley** [comment]
The first one. An employee listing, where you can change the job roles filter and it adjusts the results.

All of that is in place, and we are using a manually updated index already. 

We just need a way to keep that index up to date automatically, from the possible values of the job role field in Craft, as people will forget to update the index

**Comment by timkelty** [comment]
Ok – yeah I don't think separate indices is the right option here.

Can you send you current scout.php config?

**Comment by davebeesley** [comment]
Yeah, is there a support address I can send it to?

**Comment by timkelty** [comment]
@davebeesley tim@fusionary.com

**Comment by davebeesley** [comment]
Hey Tim.
I have sent over the `scout.php` file as requested. Hopefully GSuite doesn't gobble it up.

**Comment by janhenckens** [comment]
Going to close this as stale, feel free to report a new issue should you still have this problem.
