### ISSUE TITLE
Element not removed when "skipped" if already in index

### ISSUE THREAD

**Issue by degraaf** [studioespresso/craft-scout#148]
We have a "Do not index" option on entries, which we use to flag in our transformer to skip entries from being indexed.

However, if an entry is already indexed and the empty array is returned, the element is not removed. We need to run an index refresh to ensure entries previously indexed are removed and then valid entries re-added.

Is there a way to trigger removal of an entry from the index without flushing the entire index?

**Comment by janhenckens** [comment]
Hey @degraaf, not sure how relevant this is now but I'm going through issues so here goes :)
I think the best way to handle is to listen for the `Elements::EVENT_BEFORE_SAVE_ELEMENT` and compare value of the "Do not index" field. If it changed from `false` to `true`, you can call `$event->sender->unsearchable()`. That will remove the element from any index it is in.

Feel free to reopen this or create a new issue if you're stilling having issues with this!
