### ISSUE TITLE
Exception error when using custom Transformer class

### ISSUE THREAD

**Issue by justinholtweb** [studioespresso/craft-scout#161]
We have two custom Transformer classes declared in our config, but after a recent update to Craft 3.4.23 and update of Scout to 2.3.0 the Scout settings admin screen no longer loads, and instead triggers a 500 error stating that the classes can't be declared because they are already in use. 

The configuration follows the docs regarding how to setup, declare, and then call the custom classes so I'm not sure whats going on. I'm happy to provide the scout.php config if needed.

"PHP Compile Error – yii\base\ErrorException
Cannot declare class StoreTransform, because the name is already in use"

We're running PHP 7.1.33.

**Comment by janhenckens** [comment]
Hey @justinholtweb, not sure how relevant this is now but I'm going through issues so here goes :)

I tried this with 2 custom transformers on current versions of Craft and Scout and I can't reproduce this.
If you're still having this issue, feel free to reopen this issue. Thanks!
