### ISSUE TITLE
Using "*" in element criteria makes utility panel fail

### ISSUE THREAD

**Issue by ockam** [studioespresso/craft-scout#163]
FWIW - you can query `*` or an array on sites now in Craft, so if you didn't need them in different algolia indices, you could do this in one criteria.

_Originally posted by @timkelty in https://github.com/riasvdv/craft-scout/issues/95#issuecomment-616587453_

**Comment by ockam** [comment]
As suggested by @timkelty, you can use `*` to query multiple sites and aggregate them in a single indice. 

It works fine, except for the Utility panel, which expect a single siteId:
```
Argument 1 passed to craft\services\Sites::getSiteById() must be of the type int, string given, called in /vendor/rias/craft-scout/src/utilities/ScoutUtility.php on line 37
```
Could you add a check for `*` or `is_array` and set the site to `"Multiple sites"` or a list of the sites?

**Comment by janhenckens** [comment]
This was fixed in today's release!
