### ISSUE TITLE
Feature request:  Setting to prevent indexing relations

### ISSUE THREAD

**Issue by twosixcode** [studioespresso/craft-scout#173]
Currently during an indexing task, Scout also indexes each of the relations on an entry. In our case we're working with content with 10+ relations per entry over 1000's of entries. So this is driving up the number of Algolia Record Operations beyond what our plan allows. 

For our use case, a setting to disable indexing of relations would be very helpful. Something like `$depth = 1` or `$indexRelations = false` would be ideal.

**Comment by timkelty** [comment]
@twosixcode can you try this branch?

```
    "rias/craft-scout": "dev-optional-relations as 2.4.0",
```

and set `'indexRelations' => false,` in your `config/scout.php` file?

**Comment by twosixcode** [comment]
This worked perfectly. I toggled `indexRelations` on/off and observed the Algolia logs after making an entry save in Craft. With `indexRelations` set to `false`, the logs only showed a POST request for the entry itself. With it set to `true` I saw POST requests for all the relations on that entry.

**Comment by lmaucoin** [comment]
Thanks for the fix @timkelty! Seems very simple, but effective. We have a similar scenario that will greatly benefit from this. 👍

**Comment by janhenckens** [comment]
This was released in version 2.5.0 https://github.com/studioespresso/craft-scout/blob/master/CHANGELOG.md#250---2021-10-07
