### ISSUE TITLE
Index not updated after creating or updating Element

### ISSUE THREAD

**Issue by nicolasbinet** [studioespresso/craft-scout#176]
Index are not being updated due to eager loaded relationships not being loaded.
It works fine from the CLI, but the job doesn't load those relationships the same way and returns an EntryQuery instead of an array.
How can we homogenize the returned Element passed to the transformer ?

```
ScoutIndex::create('PRODUCT')
    ->elementType(Entry::class)
    ->criteria(function (EntryQuery $query) {
        return $query->section('product')
            ->with([
                'accessories',
            ]);
    })
    ->transformer(function (Entry $product) {
        $data = [
            'objectID' => $product->id,
            'url' => $product->url,
            'code' => $product->code,
            'title' => $product->title,
            'accessories' => array_map(function($accessory) {
                return $accessory->title;
            }, $product->relatedAccessories),
            'postDate' => $product->postDate->getTimestamp(),
        ];

        return $data;
    }),

```

**Comment by timkelty** [comment]
@nicolasbinet to be clear, if you remove the eager loading (`with`), things work as expected?

**Comment by nicolasbinet** [comment]
@timkelty Yes it does.
Removing the with() call and adding ->all to relatedAccessories fixes the problem.

```
ScoutIndex::create('PRODUCT')
    ->elementType(Entry::class)
    ->criteria(function (EntryQuery $query) {
        return $query->section('product');
    })
    ->transformer(function (Entry $product) {
        $data = [
            'objectID' => $product->id,
            'url' => $product->url,
            'code' => $product->code,
            'title' => $product->title,
            'accessories' => array_map(function($accessory) {
                return $accessory->title;
            }, $product->relatedAccessories->all()),
            'postDate' => $product->postDate->getTimestamp(),
        ];

        return $data;
    }),

```

**Comment by timkelty** [comment]
Thanks @nicolasbinet.
Surprised this hasn't come up before!

Short term, I suggest just avoiding eager-loading (hopefully you have a separate queue worker running, so it shouldn't matter much). I presume you are just doing this for performance, yes?

Long term, this should definitely be addressed.
PRs for 2.x are welcome, otherwise it will be addressed in 3.x.

**Comment by nicolasbinet** [comment]
@timkelty I've prepared a PR (#177)  for this problem, but I was not able to launch the test suite for it.
Let me know if you have any comment.

**Comment by timkelty** [comment]
Thank you, @nicolasbinet! Will review asap.

**Comment by nicolasbinet** [comment]
@timkelty Have you had any time to review the PR ?

**Comment by nicolasbinet** [comment]
@timkelty Any chance this will be integrated ?

**Comment by timkelty** [comment]
@nicolasbinet pinging @janhenckens, as he has taken over management of the repo.
