### ISSUE TITLE
Don't needlessly override Algolia defaults (connect_timeout)

### ISSUE THREAD

**Issue by joshuabaker** [studioespresso/craft-scout#179]
I started getting the following error, which proved quite hard to diagnose. Not a very helpful error from the API wrapper.

```
Impossible to connect, please check your Algolia Application Id.
```

In short, at least in this instance, it’s a result of having the `connect_timeout` set to 1 second by default. Could we increase this to the default of 30 as per the [official defaults](https://www.algolia.com/doc/api-reference/api-methods/configuring-timeouts/#parameters)?

**Comment by timkelty** [comment]
@joshuabaker that link says the defaults are: "PHP, Ruby, JavaScript, Python, Android, Java, Go, and Scala: 2 seconds"

At any rate, it seems like maybe we shouldn't be setting them at all by default and just be relying on the defaults, unless explicitly passed.

**Comment by joshuabaker** [comment]
@timkelty Quite right, it does say “2 seconds”.

The plugin does actually [set that value](https://github.com/riasvdv/craft-scout/blob/3bf77ca8da9f422f8cc64ca9e64c8ee986f31c8f/src/Scout.php#L56) as [1 second](https://github.com/riasvdv/craft-scout/blob/8c2ca56cc80d763ad9ff69d1bb59f6223221c12f/config/scout.php#L33), which was enough to cause an issue in our scenario.

Could we set the default config to `null` and then run a check around the current [`setConnectTimeout` call](https://github.com/riasvdv/craft-scout/blob/3bf77ca8da9f422f8cc64ca9e64c8ee986f31c8f/src/Scout.php#L56)? I think that’s what you’re proposing here anyway, right?

**Comment by timkelty** [comment]
@joshuabaker exactly!

**Comment by joshuabaker** [comment]
Going to close as stale. If anyone wants this feature, please consider opening another issue.
