### ISSUE TITLE
How to create index from entries attached to and entry field

### ISSUE THREAD

**Issue by jpcarpenter** [studioespresso/craft-scout#181]
I'm no PHP expert, so this may be something simple I'm doing wrong. I'm attempting to create an index from entries that are attached to an entry field. This entry field is on a single. What I can't figure out is how to return the entries to Algolia as individual records.

I have tried this approach within the transformer, but each entry is returned as a single record within Algolia:

```php
$featuredResources = [];
foreach ($entry->featuredResources->all() as $resource) {
    $featuredResources = array_merge($featuredResources, [[
        'title' => $resource->title,
    ]]);
}
return $featuredResources;
```

Is there another method that is better suited to accomplish this?

**Comment by timkelty** [comment]
@jpcarpenter If you want the entries of `featuredResources` to be individual records in Algolia, then you would need to have the criteria that indexed those entries (eg `section='resources'`).

Then, whatever $entry is here could be also be indexed, and cross referenced like you are doing.
