### ISSUE TITLE
Trigger index import via url (feature request)

### ISSUE THREAD

**Issue by sparkalow** [studioespresso/craft-scout#187]
It would be great if we could trigger an index import with a url and secret key similar to feed-me.

something like this maybe:
```
https://site.com/scout/index/import?name=index_name&key=296Y19nqdAQCFMkqI6dLkAorjq
```
The key could be defined in the config file or maybe in the control panel UI.

Some use cases would be allowing a client/non admin user to kickoff an import, setups with less control over cron or worker jobs could trigger imports, integration with external systems could start an import after adding data.

**Comment by timkelty** [comment]
@sparkalow If you need to it sooner, wouldn't be too hard to achieve with your own controller. Holler if you'd like help,

**Comment by timkelty** [comment]
@sparkalow awesome! I'll put it in the pipeline

**Comment by janhenckens** [comment]
Closing this for now, feels like something that should be handled outside of the plugin itself.
