### ISSUE TITLE
Sync indices with front-end form

### ISSUE THREAD

**Issue by BradleyDRyan** [studioespresso/craft-scout#201]
I have a front-end form on my site for submissions. I'd like to refresh my indices to refresh on submission. Any ideas?

**Comment by janhenckens** [comment]
If you want to add the newly created element to the index you could hook onto an `Elements::EVENT_AFTER_SAVE_ELEMENT` for example and do `$event->sender->searchable()`. That'll kick off Scout's regular "after an entry is updated" flow.

Would that be sufficient or do you want to refresh the entire index?
