### ISSUE TITLE
Support PHP 8

### ISSUE THREAD

**Issue by zizther** [studioespresso/craft-scout#210]
It would be great to support PHP 8 by supporting `tightenco/collect` 8+ or using `illuminate/collections` which may offer future proofing.
I know there are a few PR for this, but wanted to make this an issue we can follow.

**Comment by janhenckens** [comment]
Hey @zizther! Thanks for bringing it up again, definitely something I want to fix asap. Will have a look at the PR's and at getting the tests to run across versions. 

Would you be up for doing some testing if/when I get it up & running on a branch?

**Comment by zizther** [comment]
For sure. More than happy to test!

**Comment by janhenckens** [comment]
@zizther you can test the PHP8 branch by changing the line for the package in your `composer.json` to:

`"studioespresso/craft-scout": "dev-php8 as 2.5.0"`

And then running composer update.

Let me know if you run into any issues! (tests don't work yet as this also upgrades PHPUnit, working on that)

**Comment by zizther** [comment]
@janhenckens Thanks for pushing this update.
I have tested on PHP 8.0.8 and 8.0.10, I have not noticed any issues yet.

I am going to be using this a bit more over the next couple of days, I will flag any issues I see.

**Comment by janhenckens** [comment]
@zizther Have you run into any issues so far?

**Comment by zizther** [comment]
@janhenckens I've been playing around and doing what I had done before, which probably doesn't cover every use case, but from what I've done I have not encountered any issues. It flushes and reindexes the entries fine, all data is good.
From my POV this is looking good.

**Comment by janhenckens** [comment]
This was fixed in 2.6.0, which is out now!
