### ISSUE TITLE
Truncate Text String

### ISSUE THREAD

**Issue by pixelbeatcreative** [studioespresso/craft-scout#211]
Can anyone assist on how you would truncate a text string either by characters or words? I have a text field but only want either 110 characters or 15 words to be used as a summary. 

Right now I have this as my transformer:
`$description = $entry->businessDescription`

And this in the return:
`'description' => $description,`

Any help would be greatly appreciated.

**Comment by pixelbeatcreative** [comment]
Can anyone point me in the right direction or assist me with this. I'm still struggling and any help will be greatly appreciated.

**Comment by janhenckens** [comment]
Could you give this a try @pixelbeatcreative? https://stackoverflow.com/questions/965235/how-can-i-truncate-a-string-to-the-first-20-words-in-php

**Comment by pixelbeatcreative** [comment]
@janhenckens Thank you so much for pointing me in the right direction. Would it be possible to help me format it for this plugin? I've never developed in PHP and am more of a noob to these more advanced techniques. I just tried the below code and it doesn't work. I'm thinking I need to somehow truncate the text before I call it in the return. Am I anywhere close? And again, I TRULY appreciate you taking the time to help. 

`->transformer(function (\craft\elements\Entry $entry) {
                $description = $entry->businessDescription; 
               
                
                /* Attempting to truncate text */
                function limit_text($description, $limit) {
                    if (str_word_count($description, 0) > $limit) {
                        $words = str_word_count($description, 2);
                        $pos   = array_keys($words);
                        $description  = substr($description, 0, $pos[$limit]) . '...';
                    }
                    return $description;
                }


return [
                    'description' => $description,
                ];
            }) `

**Comment by janhenckens** [comment]
So you can put this at the bottom of your scount config file, outside the config array:

```
 function limit_word_count($entry, $limit = 10) {
    if (str_word_count($entry->body, 0) > $limit) {
        $words = str_word_count($entry->body, 2);
        $pos   = array_keys($words);
        $description  = substr($entry->body, 0, $pos[$limit]) . '...';
    }
    return $description;
}
```

and then in your transformer you do `$body = limit_word_count($entry, 10);`

That should do the trick :)

**Comment by pixelbeatcreative** [comment]
@janhenckens Thank you, thank you, thank you!!  I got it working now :)

**Comment by pixelbeatcreative** [comment]
Just in case anyone else needs this, I had to edit the above code a bit and then I added an else statement for those items that already had less than 15 characters.

`function limit_word_count($entry, $limit = 15) {
    if (str_word_count($entry->body, 0) > $limit) {
        $words = str_word_count($entry->body, 2);
        $pos   = array_keys($words);
        $entry  = substr($entry->body, 0, $pos[$limit]) . '...';
    } else {
        $entry  = substr($entry->body, 0);
    }
    return $entry;
}`
