### ISSUE TITLE
Syncing Expired Entries

### ISSUE THREAD

**Issue by pixelbeatcreative** [studioespresso/craft-scout#212]
If you set an expiration date at the time an entry is created, when that expiration date arrives, will Algolia somehow be synced, or does the entry need to be manually saved in order to be synced with Algolia?

Is there any way to automate this if it isn't already?

**Comment by timkelty** [comment]
The failsafe way to do this is to index the expiry date, and then filter those out on the frontend (numeric filter).

Additionally, you can run a cron that checks for newly expired entries and resaves/reindexes them, but for it to always be instant, you should filter them out from your requests.

**Comment by pixelbeatcreative** [comment]
Thank you so much for your help! Do you know if there are docs somewhere where I can see an example of how to do that? Algolia doesn't provide much help on how to do that type of stuff

**Comment by timkelty** [comment]
@pixelbeatcreative let me see if I can dig up an example…

**Comment by timkelty** [comment]
@pixelbeatcreative for the frontend bit, you'll want to use a `filter`: https://www.algolia.com/doc/guides/managing-results/refine-results/filtering/how-to/filter-by-numeric-value/?client=javascript

First, make sure your transformer is indexing the element's`expiryDate` as a timestamp.

Then on the client-side, when you query, filter on that with the current date as the value:

```
const timestamp = Math.floor(new Date() / 1000);
index.search('query', {
  filters: `expiryDate < 100`
}).then(({ hits }) => {
  console.log(hits);
});
```

If you're using instantsearch/react, you would use the [configure component](https://www.algolia.com/doc/api-reference/widgets/configure/react/):

```
import { Configure } from 'react-instantsearch-dom';
const timestamp = Math.floor(new Date() / 1000);
const filters = `expiryDate >= ${timestamp}`
<Configure
  filters={filters}
/>
```

**Comment by pixelbeatcreative** [comment]
@timkelty Thank you so so much for this!!! I greatly appreciate your assistance, this helps a ton! Cheers!

**Comment by janhenckens** [comment]
Thanks @timkelty!

**Comment by pixelbeatcreative** [comment]
Just in case anyone needs this, another way to accomplish this is by using the configure widget. "expireDate" is the name of the attribute.

```const timestamp = Math.floor(new Date() / 1000);

search.addWidgets([
    instantsearch.widgets.configure({
        filters: `expireDate > ${timestamp}`,
    }),
]); ```
