### ISSUE TITLE
Multi-site support for Craft v3.4.*

### ISSUE THREAD

**Issue by Alxmerino** [studioespresso/craft-scout#224]
I have a site where I need to index entries in all my sites to the same index. See code bellow

```
public function index()
{
    return ScoutIndex::create($this->indexName())
        ->elementType($this->elementType())
        ->criteria(function (EntryQuery $query) {
            return $query->siteId('*')->section('assets');
        })
        ->transformer($this->transformer())
        ->indexSettings($this->indexSettings())
        ->splitElementsOn($this->splitElementsOn());
}
```
When I run this it gives me an error 

```
TypeError
Argument 1 passed to craft\services\Sites::getSiteById() must be of the type int, string given, called in /var/www/vendor/rias/craft-scout/src/utilities/ScoutUtility.php on line 38
```

This is because Craft 3.4 has a different implementation for the `getSiteById` function than on more recent versions, I cannot upgrade to a more recent version of Craft so I'm hoping someone has a workaround for this.

Thank you and thank you for this great plugin!

**Comment by janhenckens** [comment]
Hey @Alxmerino, which version of Craft are you on specifically? I'm testing on 3.4.10 with this in my index config:

`return $query->section('events')->siteId('*');`

and that works.

**Comment by janhenckens** [comment]
Also could you check which version of Scout you are running? This was fixed in https://github.com/studioespresso/craft-scout/issues/163, which was included in version 2.4.1, released on 13/8/21.

**Comment by Alxmerino** [comment]
Hi @janhenckens,

I'm running Craft 3.4.30 and Scout 2.3.1 which I believe it's the latest official release.

**Comment by janhenckens** [comment]
You should be able to install 2.5.0 through composer (https://packagist.org/packages/studioespresso/craft-scout) or through Craft's updater!

**Comment by Alxmerino** [comment]
I'll give that a try and report back, thank you!

**Comment by janhenckens** [comment]
Closing this for now @Alxmerino, feel free to reopen if you're still having the problem.
