### ISSUE TITLE
No reindexing on EVENT_AFTER_MOVE_IN_STRUCTURE

### ISSUE THREAD

**Issue by andygrn** [studioespresso/craft-scout#225]
Scout v1 had an event handler for Element::EVENT_AFTER_MOVE_IN_STRUCTURE, to reindex when elements were moved inside structures (important if you're indexing entry order). Scout v2 seems to have lost this feature.

An `it_attaches_to_the_element_move_in_structure` test does exist in tests/unit/EventHandlersTest.php, but it looks to be testing the wrong thing.

**Comment by janhenckens** [comment]
Looks like `Element::EVENT_AFTER_MOVE_IN_STRUCTURE` doesn't include the actual `element` that's being saved:

https://github.com/craftcms/cms/blob/4330199e5b7001ca85b9d919d81e465dcc275742/src/base/Element.php#L4220-L4227

So I'm not sure this can be done at the moment.

**Comment by andygrn** [comment]
`$event->sender` should give you the element, although Craft seems to fire an update event on move anyway, and doesn't fire the after_move event for other elements that have been shifted, so I'm not sure this would even be useful.
