### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by qrazi** [studioespresso/craft-scout#226]
I am having 7 tests failing when running the testsuite locally. Not entirely sure why. Anyone any idea?

- PHP version 7.4.26
- using the docker compose file for the DB
- Craft CMS (in composer.lock): 3.7.26
- master branch
- command executed: `php vendor/bin/codecept run unit`

Output (result):

```
There were 7 failures:

---------
1) EventHandlersTest: It_attaches_to_the_element_save_event_once
 Test  tests/unit/EventHandlersTest.php:it_attaches_to_the_element_save_event_once
Failed asserting that 2 matches expected 1.
#1  /home/qrazi/Workspace/craft-scout/tests/unit/EventHandlersTest.php:121

---------
2) EventHandlersTest: It_also_updates_related_elements
 Test  tests/unit/EventHandlersTest.php:it_also_updates_related_elements
Failed asserting that 2 matches expected 1.
#1  /home/qrazi/Workspace/craft-scout/tests/unit/EventHandlersTest.php:143

---------
3) EventHandlersTest: It_doesnt_update_related_elements_when_index relations_is_false
 Test  tests/unit/EventHandlersTest.php:it_doesnt_update_related_elements_when_indexRelations_is_false
Failed asserting that 2 matches expected 0.
#1  /home/qrazi/Workspace/craft-scout/tests/unit/EventHandlersTest.php:169

---------
4) EventHandlersTest: It_attaches_to_the_element_move_in_structure
 Test  tests/unit/EventHandlersTest.php:it_attaches_to_the_element_move_in_structure
Failed asserting that 2 matches expected 1.
#1  /home/qrazi/Workspace/craft-scout/tests/unit/EventHandlersTest.php:200

---------
5) EventHandlersTest: It_attaches_to_the_element_restore_event
 Test  tests/unit/EventHandlersTest.php:it_attaches_to_the_element_restore_event
Failed asserting that 2 matches expected 1.
#1  /home/qrazi/Workspace/craft-scout/tests/unit/EventHandlersTest.php:213

---------
6) EventHandlersTest: It_attaches_to_the_element_after_delete_event
 Test  tests/unit/EventHandlersTest.php:it_attaches_to_the_element_after_delete_event
Failed asserting that 2 matches expected 1.
#1  /home/qrazi/Workspace/craft-scout/tests/unit/EventHandlersTest.php:225

---------
7) EventHandlersTest: It_also_updates_related_elements_before_delete
 Test  tests/unit/EventHandlersTest.php:it_also_updates_related_elements_before_delete
Failed asserting that 2 matches expected 1.
#1  /home/qrazi/Workspace/craft-scout/tests/unit/EventHandlersTest.php:247

FAILURES!
Tests: 86, Assertions: 249, Failures: 7.
```

**Comment by janhenckens** [comment]
Hey @qrazi, I've been struggling with these EventHandlersTest.php tests for a couple of weeks too. Not sure what is causing the code to be run twice, while the event itself is only fired once.

I've debugged it during normal operations and can confirm it only happens when running the tests.
Eager to get these fixed too, I'll keep working it.

**Comment by janhenckens** [comment]
No worries, it's just been bugging me that I kind find what the problem is 😀

**Comment by qrazi** [comment]
Pretty sure I found the cause for this particular type of failing, but noticing 3 others failed still.. Digging a bit deeper.

**Comment by janhenckens** [comment]
Cool, feel free to make a PR when/if you find something!

**Comment by qrazi** [comment]
@janhenckens Quick question; the test `it_doesnt_update_related_elements_when_indexRelations_is_false` fails as well, expects `0` cached, but finds `1`. I think that is because `saveElement` always updates an Entry's updatedDate field (see https://github.com/studioespresso/craft-scout/blob/master/tests/unit/EventHandlersTest.php#L167), so `1` should actually be expected? What do you think?

**Comment by janhenckens** [comment]
Hey @qrazi, sorry about the late reply!

i think you're on to something with this specific test. We're testing if a related element gets indexed (in this case it shouldn't) so element 1 gets saved and should expect `1`,  element 2 (the related element) doesn't get saved and should expect `0`.

In my install, the save of element 1 actually results in `2` in cache and I can't figure out why. The same thing happens for the other tests in this classs. Are you seeing the same thing?

**Comment by qrazi** [comment]
I got side-tracked in my personal life a bit, so haven't been able to create PR(s). Will try to get to it soon, but in any case; there are tests that create a new plugin instance (`$scout = new Scout('scout');`). But, the test suites bootstrapping code already registered and booted the plugin. So the plugin's `init()` function gets executed twice. This in turn means that the Event Handlers are registered twice (for both instances of `Scout`), and the test fails with $actual = 2 where $expected = 1.

It's described a bit rambly, I know, but perhaps since I haven't gotten to a PR yet shares my findings already somewhat.

**Comment by janhenckens** [comment]
Doing `$scout = Scout::getInstance();` instead of `$scout = new Scout();` actually does the trick 😃. Thanks for that man, that's been bothering me for a while now!

Pushing this to develop so make sure you start any PR's from there.
