### ISSUE TITLE
Formatting Dates

### ISSUE THREAD

**Issue by pixelbeatcreative** [studioespresso/craft-scout#229]
I have my return for my post date set:
 
`'postDate' => $entry->postDate->format(\DateTime::ATOM)`

but I'm trying to figure out how to transform it to a date only, `Jan. 15, 2022` format. Is there a way to do this? Any help would be greatly appreciated. PS. I'm not a strong PHP developer. :)

**Comment by joshuapease** [comment]
Hi @pixelbeatcreative! https://www.php.net/manual/en/datetime.format.php is the PHP documentation you'd be looking for. 

Date formatting is a native PHP feature, so this isn't unique to the Scout plugin and can be used anywhere you have a [DateTime](https://www.php.net/manual/en/class.datetime.php) object. 

To achieve your desired format, you'd do something like this. I'd recommend looking at those PHP docs and seeing what they say about the `M`, `j`, and `Y`, characters. 
```
'postDate' => $entry->postDate->format('M. j, Y')
```

**Comment by pixelbeatcreative** [comment]
Ah! Thank you so much for your help!

**Comment by janhenckens** [comment]
Thanks for helping out @joshuapease!
