### ISSUE TITLE
Scout Utilities page button spacing

### ISSUE THREAD

**Issue by jamesmacwhite** [studioespresso/craft-scout#245]
The buttons for index related actions on the Utilities page do not have equal spacing between the flush and update settings button.

![image](https://user-images.githubusercontent.com/8067792/178777674-257da959-18f2-4965-8f64-08e19835b672.png)

**Comment by jamesmacwhite** [comment]
I believe it's because the first three form controls are in their own form container, then the next two are in their own form container after.

**Comment by janhenckens** [comment]
Should be fixed in the next release:

![Screenshot 20221024-190858-8Urr7qTY@2x](https://user-images.githubusercontent.com/755428/197585051-5f9829c7-cba6-42a0-8871-8bccd5f9b64d.png)
