### ISSUE TITLE
Queue priority

### ISSUE THREAD

**Issue by chrismou** [studioespresso/craft-scout#258]
I noticed that there's a setting for queue priority, but there isn't a UI option to change it on the settings page.

Is there a reason for it? And if not, would you accept a PR to add it?

**Comment by janhenckens** [comment]
Hey @chrismou, I think the option isn't there because most people configure the plugin through a config file (`scout.php`) since that's easier across environments.


But I agree that having it be hidden is not ideal either so I'd be happy to accept a PR for it :).
