### ISSUE TITLE
[STU-130] Split elements not deleted on content update

### ISSUE THREAD

**Issue by AlexPagnotta** [studioespresso/craft-scout#259]
Hello,

It seems that when updating an entry split into multiple rows (splitElementsOn), the previous rows are only deleted if the new value for the property has 2 elements or more, so basically if _null_, an _empty array_, or an _array with 1 item_ is returned for the property on the transformer, the previous rows are not deleted and left as orphans.

I'm currently using the split elements functionality for a rich text field on craft, where each paragraph is split into a new row, and this means that if I currently have a text with 4 paragraphs (so 4 rows on algolia), then I edit the text and remove all the paragraphs, I'm now left with 5 items, a correct one with an empty text, and the previous 4 rows.

<sub>[STU-130](https://linear.app/studio-espresso/issue/STU-130/split-elements-not-deleted-on-content-update)</sub>

**Comment by jasonlav** [comment]
https://github.com/studioespresso/craft-scout/blob/master/README.md#-splitelementsonarray-keys Note the "Important" callout below the method description about facets.

**Comment by janhenckens** [comment]
I've tagged this in 3.3.3-beta.2 - since we already had a beta running to fix ongoing issues with deletions not going through in some cases (with split elements as well). 

Could you give this a try and see if it fixes things?
