### ISSUE TITLE
Make it possible to set priority of IndexElement job

### ISSUE THREAD

**Issue by almeric** [studioespresso/craft-scout#271]
Hi,

First off, thanks for the great plugin!

We're currently using it on a site with a lot of mutations on a lot of entries resulting in (you guessed it) a lot of `Indexing Element` jobs.

It would be great if we could set the priority of these jobs through the config file so other jobs don't get pushed to the back of the queue. 

There's already a `priority` option in the config file, but it seems that one's not used here for example:
https://github.com/studioespresso/craft-scout/blob/master/src/Scout.php#L166C25-L168

Thanks

**Comment by janhenckens** [comment]
Hey @almeric! Yeah, that setting should be used for that job as well.

Could you just confirm which version of the plugin - and of Craft - you're running at the moment? Thanks!

**Comment by almeric** [comment]
Sure:

Craft : 4.5.3 
Scout: 3.1.2

**Comment by janhenckens** [comment]
hey @almeric, a fix for this is out in 3.1.3. Can you give that a try? Thanks!

**Comment by almeric** [comment]
@janhenckens Awesome, thanks for the quick fix! Just looked at the queue and all seems to be working great.

Thanks again
