### ISSUE TITLE
Clarify the license

### ISSUE THREAD

**Issue by barnslig** [studioespresso/craft-scout#272]
Thank you very much for the great plugin! However, I am wondering about the actual license of the code.

On the Craft Plugin Store, it is stated multiple times that the plugin is licensed under MIT license: [plugins.craftcms.com/scout](https://plugins.craftcms.com/scout?craft4). Also, the composer.json states the MIT license.

However, the LICENSE.md file contains the proprietary Craft license: [LICENSE.md](https://github.com/studioespresso/craft-scout/blob/master/LICENSE.md)

Please clarify the actual license of the code and change the license notes accordingly 🙂

**Comment by janhenckens** [comment]
Hey @barnslig, thanks for reporting that - the license in the repo was still the one set by the previous maintainer. I changed it to MIT (still on develop only at the moment, will release it to master with the next release).
