### ISSUE TITLE
[STU-51] Deprecation Warning: Disabling the queue option

### ISSUE THREAD

**Issue by wietsedecnijf** [studioespresso/craft-scout#274]
We disabled the queue option because our workers couldn't keep up with the amount of queue jobs being created.
It would be great to still have the option.

<sub>[STU-51](https://linear.app/studio-espresso/issue/STU-51/deprecation-warning-disabling-the-queue-option)</sub>

**Comment by janhenckens** [comment]
This is still in the craft 5 release and will be maintained for now, I removed the deprecation notice.
