### ISSUE TITLE
Saving entry using queue runner only index the primary site version of the entry

### ISSUE THREAD

**Issue by mathg** [studioespresso/craft-scout#278]
When saving an Entry not in a primary site, the after save hook for indexing gets triggered but it only indexes the entry from the primary site. The relations are saved correctly in all sites.

The Refresh buttons index them properly.

If I change the 'queue' param to false in config/scout.php it works properly, which means the queue building isn't indexing the right site version of the entry.

**Comment by janhenckens** [comment]
Hey @mathg, I'll reopen #266 and close this issue.
