### ISSUE TITLE
[STU-65] Only one index shows in the control panel

### ISSUE THREAD

**Issue by tyssen** [studioespresso/craft-scout#280]
I have two indices configured in `scout.php` e.g.

    return [
        'indices' => [
            \rias\scout\ScoutIndex::create('reviews')
            ->elementType(\craft\elements\Entry::class)
            ->criteria(function (\craft\elements\db\EntryQuery $query) {
                return $query->section('reviews');
            })
            ->transformer(function (\craft\elements\Entry $entry) {

                return [
                    'title' => $entry->title,
                    …
                ];
            })
        ],
        [
            \rias\scout\ScoutIndex::create('articles')
            ->elementType(\craft\elements\Entry::class)
            ->criteria(function (\craft\elements\db\EntryQuery $query) {
                return $query->section('articles');
            })
            ->transformer(function (\craft\elements\Entry $entry) {

                return [
                    'title' => $entry->title,
                    …
                ];
            })
        ],
    ];

but when visiting `/utilities/scout-indices` I can only see the first one listed. Is that to be expected?

<sub>[STU-65](https://linear.app/studio-espresso/issue/STU-65/only-one-index-shows-in-the-control-panel)</sub>

**Comment by janhenckens** [comment]
Hey @tyssen, that seems like a bug (possibly introduced in #275). Will have a look and try to have a bugfix out over the weekend.

**Comment by janhenckens** [comment]
Hey @tyssen, it looks like your second index isn't in the "indices" key, is that just in this example?

Could you also let me know which version of Craft & Scout your are running? I can't reproduce it on my end with the current release (3.3.0).

**Comment by tyssen** [comment]
@janhenckens yep, sorry, I hadn't set that up quite right. Fixed now and I can see both of them in the control panel. Sorry for wasting your time.

**Comment by janhenckens** [comment]
No worries!
