### ISSUE TITLE
[STU-166] Debug logging left in 4.10 release

### ISSUE THREAD

**Issue by gilleard** [studioespresso/craft-scout#312]
I believe the `Craft::error` call introduced from [this commit](https://github.com/studioespresso/craft-scout/commit/529f701f12a501e5530015a73c4280e3289ef382#diff-3708ad1a94243528e234ca83941b909e3ca5a5b650c34e1f648f8b9faf954541R66) will just have been for development purposes, and shouldn't be in the 4.10 release?

We're using [Sentry Logger](https://github.com/diginov/craft-sentry-logger) so this call is triggering that when running the queue. We can exclude via pattern matching but thought I'd flag, seems like it's in there by mistake.

Thanks!

<sub>[STU-166](https://linear.app/studio-espresso/issue/STU-166/debug-logging-left-in-410-release)</sub>

**Comment by janhenckens** [comment]
Thanks for catching that @gilleard, meant as debugging as you said and it got committed by accident. Will be removed in the next release!

**Comment by janhenckens** [comment]
Fixed in 4.1.1
