### ISSUE TITLE
Exception thrown in /admin/utilities/scout-indices when index doesn't exist

### ISSUE THREAD

**Issue by alexmillman23** [studioespresso/craft-scout#343]
I use the dashboard sometimes to run the import which creates the index. I don't remember an exception being thrown before if it doesn't exist.

**Comment by janhenckens** [comment]
Not a change on the plugin's end as for as I can see, but I can catch that error so you can keep doing the first sync from the CP.

@alexmillman23  Is Craft 5 ok for this or would be you also need this back ported to the Craft 4 version?

**Comment by alexmillman23** [comment]
@janhenckens We're still on 4, so that would be appreciated!

Thank you!

**Comment by janhenckens** [comment]
Fixed in today's updates! Version 4.1.2 for Craft 4 & 5.0.2 for Craft 5

Can you update and try again? @alexmillman23 
Let me know should you run into anything else! :)

**Comment by alexmillman23** [comment]
@janhenckens Appreciate this! Works great :)
